#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\LiquidTag\Device;
use App\LiquidTag\Embed;
use App\LiquidTag\Guide;
use App\LiquidTag\YouTube;
use Minicli\App;
use Minicli\Exception\CommandNotFoundException;


$app = new App();
$app->setSignature('
 _      ____  ____   ____    ____  ____   ____   ____  ____  
| |    |    ||    \ |    \  /    ||    \ |    | /    ||    \ 
| |     |  | |  o  )|  D  )|  o  ||  D  ) |  | |  o  ||  _  |
| |___  |  | |     ||    / |     ||    /  |  | |     ||  |  |
|     | |  | |  O  ||    \ |  _  ||    \  |  | |  _  ||  |  |
|     | |  | |     ||  .  \|  |  ||  .  \ |  | |  |  ||  |  |
|_____||____||_____||__|\_||__|__||__|\_||____||__|__||__|__|

Type "./librarian help" for help with available commands.
');

$app->librarian->boot();

$app->content->registerTagParser('newtube', new YouTube());
$app->content->registerTagParser('device', new Device());
$app->content->registerTagParser('embed', new Embed());
$app->content->registerTagParser('guide', new Guide());

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $notFoundException) {
    if ($app->config->debug) {
        $app->error("Command Not Found.");
    }
    return 1;
} catch (Throwable | Exception $exception) {
    if ($app->config->debug) {
        $app->error("An error occurred:");
        $app->error($exception->getMessage());
    }
    return 1;
}

return 0;

